import { Injectable, signal, computed } from '@angular/core';

export type Lang = 'es' | 'en';

const translations = {
  es: {
    navCollection: 'Colección',
    navNew: 'Nuevos',
    navSale: 'Ofertas',
    brand: 'ATHENA BRAND',
    tagline: 'Moda que define tu esencia',
    heroSub:
      'Descubre nuestra colección exclusiva. Prendas diseñadas para quienes no siguen tendencias — las crean.',
    shopNow: 'Explorar colección',
    newIn: 'Nuevo ingreso',
    featured: 'Destacado',
    sale: 'Oferta',
    outOfStock: 'Sin stock',
    inStock: 'En stock',
    addToCart: 'Agregar',
    viewDetails: 'Ver detalle',
    filters: 'Filtros',
    search: 'Buscar prendas...',
    allCategories: 'Todas las categorías',
    priceRange: 'Rango de precio',
    clearFilters: 'Limpiar filtros',
    noProducts: 'Sin productos',
    noProductsSub: 'Intenta ajustar los filtros',
    loading: 'Cargando colección...',
    showing: 'Mostrando',
    products: 'productos',
    previous: 'Anterior',
    next: 'Siguiente',
    cart: 'Carrito',
    heroTagline: 'MENOS RUIDO MAS ESENCIA',
    heroPills: ['100% Prendas Premium', 'Envíos a toda Colombia', 'Atención por WhatsApp'],
    categories: {
      chaquetas: 'Chaquetas',
      deportivos: 'Deportivos',
      hombre: 'Hombre',
      'hoodies-sacos': 'Hoodies-Sacos',
      mujer: 'Mujer',
    },
    productTranslations: {},
    storeSince: 'COLOMBIAN STORE SINCE 2025',
    items: 'PRENDAS',
    retry: 'Reintentar',
    noResults: 'Sin resultados',
    noResultsSub: 'No hay prendas en esta categoría por el momento.',
    viewAll: 'Ver todo',
    sectionNew: 'NUEVOS',
    sectionSale: 'OFERTAS',
    fullCollection: 'COLECCIÓN COMPLETA',
    newBadge: 'NUEVO',
    soldOutBadge: 'AGOTADO',
    consult: 'Consultar',
    gallery: 'GALERÍA',
    season: 'TEMPORADA 2025',
    rightsReserved: 'Todos los derechos reservados.',
    adminPanel: 'Panel Admin',
    reviews: 'reseñas',
    off: 'OFF',
    sizes: 'Tallas',
    color: 'Color',
    sortBy: 'Ordenar por',
    sortRelevance: 'Relevancia',
    sortPriceLow: 'Precio: menor a mayor',
    sortPriceHigh: 'Precio: mayor a menor',
    sortNewest: 'Más recientes',
    free_shipping: 'Envío gratis en pedidos +$150k',
    secure: 'Pago 100% seguro',
    returns: 'Devoluciones gratis 30 días',
    // Product detail
    backToShop: '← Volver a la tienda',
    selectSize: 'Selecciona una talla',
    sizeRequired: 'Por favor selecciona una talla',
    quantity: 'Cantidad',
    max: 'Máx',
    addToCartBtn: 'Agregar al carrito',
    adding: 'Agregando...',
    viewCart: 'Ver carrito',
    sku: 'SKU',
    category: 'Categoría',
    availableStock: 'Stock disponible',
    stockForSize: 'Stock para talla',
    units: 'unidades',
    created: 'Creado',
    freeShippingBadge: '✓ Envío gratis en pedidos +$150k',
    returnsBadge: '✓ Devoluciones gratis 30 días',
    secureBadge: '✓ Pago seguro',
    fastDelivery: '✓ Entrega rápida',
    addedToCart: 'agregado al carrito',
    outOfStockBadge: 'Sin Stock',
    inStockBadge: 'En Stock',
    loadingProduct: 'Cargando producto...',
    logout: 'Cerrar sesión',
    contactWhatsApp: 'Consultar por WhatsApp',
  },
  en: {
    navCollection: 'Collection',
    navNew: 'New In',
    navSale: 'Sale',
    brand: 'ATHENA BRAND',
    tagline: 'Fashion that defines your essence',
    heroSub:
      "Discover our exclusive collection. Garments designed for those who don't follow trends — they set them.",
    shopNow: 'Explore collection',
    newIn: 'New in',
    featured: 'Featured',
    sale: 'Sale',
    outOfStock: 'Out of stock',
    inStock: 'In stock',
    addToCart: 'Add to cart',
    viewDetails: 'View details',
    filters: 'Filters',
    search: 'Search garments...',
    allCategories: 'All categories',
    priceRange: 'Price range',
    clearFilters: 'Clear filters',
    noProducts: 'No products',
    noProductsSub: 'Try adjusting your filters',
    loading: 'Loading collection...',
    showing: 'Showing',
    products: 'products',
    previous: 'Previous',
    next: 'Next',
    cart: 'Cart',
    heroTagline: 'LESS NOISE MORE ESSENCE',
    heroPills: ['100% Premium Garments', 'Shipping across Colombia', 'WhatsApp Support'],
    categories: {
      chaquetas: 'Jackets',
      deportivos: 'Sports',
      hombre: 'Men',
      'hoodies-sacos': 'Hoodies & Jackets',
      mujer: 'Women',
    },
    productTranslations: {},
    storeSince: 'COLOMBIAN STORE SINCE 2025',
    items: 'ITEMS',
    retry: 'Retry',
    noResults: 'No results',
    noResultsSub: 'No items in this category at the moment.',
    viewAll: 'View all',
    sectionNew: 'NEW IN',
    sectionSale: 'SALE',
    fullCollection: 'FULL COLLECTION',
    newBadge: 'NEW',
    soldOutBadge: 'SOLD OUT',
    consult: 'Inquire',
    gallery: 'GALLERY',
    season: 'SEASON 2025',
    rightsReserved: 'All rights reserved.',
    adminPanel: 'Admin Panel',
    reviews: 'reviews',
    off: 'OFF',
    sizes: 'Sizes',
    color: 'Color',
    sortBy: 'Sort by',
    sortRelevance: 'Relevance',
    sortPriceLow: 'Price: low to high',
    sortPriceHigh: 'Price: high to low',
    sortNewest: 'Newest',
    free_shipping: 'Free shipping on orders +$150k',
    secure: '100% secure payment',
    returns: 'Free returns 30 days',
    // Product detail
    backToShop: '← Back to shop',
    selectSize: 'Select a size',
    sizeRequired: 'Please select a size',
    quantity: 'Quantity',
    max: 'Max',
    addToCartBtn: 'Add to cart',
    adding: 'Adding...',
    viewCart: 'View cart',
    sku: 'SKU',
    category: 'Category',
    availableStock: 'Available stock',
    stockForSize: 'Stock for size',
    units: 'units',
    created: 'Created',
    freeShippingBadge: '✓ Free shipping on orders +$150k',
    returnsBadge: '✓ Free returns 30 days',
    secureBadge: '✓ Secure payment',
    fastDelivery: '✓ Fast delivery',
    addedToCart: 'added to cart',
    outOfStockBadge: 'Out of Stock',
    inStockBadge: 'In Stock',
    loadingProduct: 'Loading product...',
    logout: 'Logout',
    contactWhatsApp: 'Contact via WhatsApp',
  },
};

type Translations = typeof translations.es;

@Injectable({ providedIn: 'root' })
export class LangService {
  lang = signal<Lang>('es');
  t = computed(() => translations[this.lang()] as Translations);

  toggle(): void {
    this.lang.set(this.lang() === 'es' ? 'en' : 'es');
  }

  set(lang: Lang): void {
    this.lang.set(lang);
  }
}
